# Generated by Django 4.1.3 on 2022-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
