# Generated by Django 4.1.3 on 2022-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='agree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
